### ISSUE TITLE
Listing not test but assertions

### ISSUE THREAD

**Issue by khru** [Chemaclass/bashunit#26]
On the list of tests we are executing we are not showing the list of test running but the list of assertions happening:

![image](https://github.com/Chemaclass/bashunit/assets/6353105/f89682ef-a798-459d-9586-1c3bf0224973)

This bug could relate to this Issue: https://github.com/Chemaclass/bashunit/issues/18

**Comment by Tito-Kati** [comment]
Currently, all assertions are printing both their 'passed' and 'failed' messages, when in reality, assertions should only print the 'failed' messages. For a test to be considered 'passed', all assertions within that test must pass.

Having said that, our assertions can currently accept an optional third argument, which defines the text displayed when the assertion passes. Ideally, this text should always be the name of the test, and this third argument message should only be displayed when the assertion fails.

As examples, I mention [PHPUnit's implementations](https://docs.phpunit.de/en/10.3/assertions.html#boolean) (which support it natively, see $message) and Jest's, which supports it [through a plugin](https://github.com/mattphillips/jest-expect-message).

By the way, I don't see the implementation of this feature as mandatory, but I do find it interesting and practical.
