### ISSUE TITLE
Makefile init-hooks not working

### ISSUE THREAD

**Issue by khru** [Chemaclass/bashunit#29]
Don't know what's supposed to do but fails:

![image](https://github.com/Chemaclass/bashunit/assets/6353105/fb5c5e8b-949f-4851-8774-370c75247c60)

**Comment by Chemaclass** [comment]
Ups, that's a copy-paste from other project. We dont have git hooks in this project. I think we can simply remove that make command.

**Comment by khru** [comment]
Done
