### ISSUE TITLE
Create assertExitCode

### ISSUE THREAD

**Issue by Chemaclass** [Chemaclass/bashunit#45]
Create an assert function that verifies the exit code of the return/exit code 
- like `assertExitCode`
- and `assertNotExitCode`

**Comment by Tito-Kati** [comment]
assertNotExitCode too?

**Comment by Tito-Kati** [comment]
Is this assertion necessary? I'll provide an example of how it can be done currently without it:

![imagen](https://github.com/Chemaclass/bashunit/assets/13595197/2148a589-818a-4b3e-835f-2d405cc0b778)

**Comment by Chemaclass** [comment]
I 've got something like this in mind:
```bash
#
# Usage: assertExitCode 1 script.sh
#
function assertExitCode() {
    local expected_exit_code=$1
    shift
    local command_to_run="$*"

    $command_to_run

    local actual_exit_code=$?

    if [ $actual_exit_code -eq "$expected_exit_code" ]; then
        return 0
    else
        exit 1
    fi
}
```

But you might be right, we can easily check the last return/exit code using `$?` right after the execution of a script, that might be sufficient using an `assertEquals` right after that. Would you say, we should close this issue and wont do, at least for now, @Tito-Kati @khru ?

**Comment by khru** [comment]
It's true what @Tito-Kati says, It is also true that it could be very interesting to simplify the assertions or make them more semantic.

So I think it wouldn't be a bad assertion and would help with semantics.

**Comment by khru** [comment]
It's true what @Tito-Kati says, It is also true that it could be very interesting to simplify the assertions or make them more semantic.

So I think it wouldn't be a bad assertion and would help with semantics.

**Comment by khru** [comment]
> I 've got something like this in mind:
> ```bash
> #
> # Usage: assertExitCode 1 script.sh
> #
> function assertExitCode() {
>     local expected_exit_code=$1
>     shift
>     local command_to_run="$*"
> 
>     $command_to_run
> 
>     local actual_exit_code=$?
> 
>     if [ $actual_exit_code -eq "$expected_exit_code" ]; then
>         return 0
>     else
>         exit 1
>     fi
> }
> ```

I see value on male the assertions more semanticts and simple, so to me it's a go
> 
> But you might be right, we can easily check the last return/exit code using `$?` right after the execution of a script, that might be sufficient using an `assertEquals` right after that. Would you say, we should close this issue and wont do, at least for now, @Tito-Kati @khru ?

**Comment by Tito-Kati** [comment]
The issue with doing it the way you suggest is that the assertion is responsible for executing the command/function, which means you couldn't assert both the printed output and the response code at the same time. In other words, it couples the acting to the assertion...

**Comment by khru** [comment]
> The issue with doing it the way you suggest is that the assertion is responsible for executing the command/function, which means you couldn't assert both the printed output and the response code at the same time. In other words, it couples the acting to the assertion...

That's true, but we could implement it, simply by consulting the last execution and thus make the assert not tied to the execution

But for me the discussion is more about whether this assertion makes sense or not and I think so.

**Comment by khru** [comment]
> The issue with doing it the way you suggest is that the assertion is responsible for executing the command/function, which means you couldn't assert both the printed output and the response code at the same time. In other words, it couples the acting to the assertion...

That's true, but we could implement it, simply by consulting the last execution and thus make the assert not tied to the execution

But for me the discussion is more about whether this assertion makes sense or not and I think so.

**Comment by Chemaclass** [comment]
Oh, what about this?
```bash
#
# Usage: assertExitCode 1
#
function assertExitCode() {
    local expected_exit_code="$1"
    local actual_exit_code=$?

    if [ $actual_exit_code -eq "$expected_exit_code" ]; then
        return 0
    else
        exit 1
    fi
}
```

**Comment by Tito-Kati** [comment]
All our assertion tests are a perfect sandbox to test whichever implementation we find most suitable. In any of those tests, we should assert that the return code is correct (in addition to what they currently do, which is to assert that the appropriate message is printed).

So, we have the perfect place to experiment and see if we like the outcome or not. What do you think about adding the new assertions and adapting these tests in a single PR to see if we like the result?

**Comment by Tito-Kati** [comment]
I mean, for instance, [these tests](https://github.com/Chemaclass/bashunit/blob/main/tests/unit/assert_test.sh) should be something like this?

```bash
function test_successful_assertEquals() {
  assertEquals "" "$(assertEquals "1" "1")"
  assertExitCode "0"
}

function test_unsuccessful_assertEquals() {
  assertEquals\
    "$(printFailedTest "Unsuccessful assertEquals" "1" "but got" "2")"\
    "$(assertEquals "1" "2")"
  assertExitCode "1"
}
```

**Comment by Chemaclass** [comment]
I didn't implement `assertNotExitCode` in https://github.com/Chemaclass/bashunit/pull/49 because I thought it's not really needed... but maybe it is. What do you think, @khru @Tito-Kati ? It could be a nice easy task for @fabriziofs, for example
